platform :ios, '10.0'
use_frameworks!

target 'BigDiffer_Example' do
  pod 'BigDiffer', :path => '../'
  pod 'BigDiffer/Differ', :path => '../'
  pod 'BigDiffer/HeckelDiff', :path => '../'
  pod 'BigDiffer/DeepDiff', :path => '../'
  pod 'BigDiffer/EditDistance', :path => '../'
  pod 'BigDiffer/DifferenceKit', :path => '../'
  pod 'Eureka'

  target 'BigDiffer_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
  end
end
